-- AlterTable
ALTER TABLE "AlertEvent" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "AlertRule" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Page" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "PageAudit" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Project" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Query" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "QuerySet" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Report" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "SerpResult" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "SerpScan" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Workspace" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "WorkspaceMember" ALTER COLUMN "id" DROP DEFAULT;
